kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codegen1-may6-3-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: codegen1-may6-3-dsp-job
    namespace: codegen1-may6-3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: codegen1-may6-3-dsp-job-role
